{
  "source-provider": {
    "type": "HUB",
    "hub": {
      "url": "${guiUrl}",
      "project-name": "${projectName}",
	  "api-key": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJqdGkiOiJlNTE3MmRiMS1kMjFlLTRkMmQtOGU3NS01ZDA1ODJmODdjZDMiLCJ0aWQiOiI4YTM5N2UxMy1lZjkwLTQ4MDAtYjIwZi02ZmU3NzcwNDNiMzUiLCJodHRwczovL29sLnRlbmFudHMvcmVnaW9uIjoiRVUiLCJpYXQiOjE2NTQxODE1MzYsImlzcyI6Im9sIiwic3ViIjoiYXV0aDB8NjFlZWM0YjU0ZTY3MmMwMDY5NzgxNzUwIn0.Mh33yq5n8Af83aiqRR-Mfs4syKQZ1-CKGLtmOERl4TSNhRqUHTfS-k8Qs5K9YuBwzEEySbQJKQFRiUjVM_5lqN1xXq7Sywh4al__XjfgjTq5l_BaYuvio2du-2ObyMqWAwEpr_Kv3vgw56kAeXk260UiyZmc7xMpMNEsQ0hik7TgaHv3HYcXt9bZO0iXir7kuz4Uc97Kvuu-aD3RS2RIuz_ZnhOrCKkQPr77LoHnMtaATF3nCSVUzeqWIrjZG3UojPEyNto9Smg46RAZ1iCXlyIYvfC_UlnOgZBF1DfO0c17-VPAntpXNJkIdi7ahkTYyzz0ouQsyb0sEquf7KGyeA"
    }
  }
}
